# MySQL
spring.datasource.url=jdbc:mysql://ssafy-mysql-db.mysql.database.azure.com:3306/S14P12E205?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
spring.datasource.username=S14P12E205
spring.datasource.password=OGB7vpLp2b
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OAuth2
spring.security.oauth2.client.registration.github.client-id=Ov23lidd0cgRxJvbQrlc
spring.security.oauth2.client.registration.github.client-secret=4cf14d2fd64fc11dfa8d578556105f98cff3f2b8

jwt.secret=v3h+P6z9R2N5b8e1G4H7k0M3P6s9V2y5B8e1H4K7N0Q3T6w9z&C&F)J@NcRfUjXn

app.frontend.url=http://localhost:5173

ai.service.base-url=http://127.0.0.1:8000

encryption.secret-key=my-super-secret-key-123456

file.path=C:/codinnator/files